# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08085e97499ddcc4200e80675428656d2b1ca29996549125321adc369a7ef7ae278cdcd15207e88c7154c85ff812cf27844a6208c3f0fac923ed7962c00291bb

test:
  secret_key_base: d835ca3df107ba4daaca1af5fc48081583e2cec03013b4a31e2edae711ec4073fffd9c9a9f34450318c0f388130cf91661c145ac3e948604275968d07e1bfb31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
